apiVersion: v2
name: registry-ui
description: A Helm chart for docker registry UI
type: application
version: 1.0.2
appVersion: "1.0.2"
dependencies:
  - name: helmet
    version: 0.11.0
    repository: https://charts.companyinfo.dev
    import-values:
      - defaults
