image:
  repository: "joxit/docker-registry-ui"
  pullPolicy: IfNotPresent
  tag: "2.5.7"
ports:
  - name: http
    containerPort: 80
    protocol: TCP
livenessProbe:
  enabled: true
  httpGet:
    path: /
    port: http
readinessProbe:
  enabled: true
  httpGet:
    path: /
    port: http
