{{- if .Values.enabled }}
{{- range $name, $value := .Values.jobs }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "pg-dump-job.fullname" $ }}-{{ $name }}-cron-job
  labels:
    {{- include "pg-dump-job.labels" $ | nindent 4 }}
spec:
{{- $backupDirectory := $value.backupDirectory | default $.Values.backupDirectory -}}
{{- with $value }}
  schedule: {{ .schedule | quote}}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          volumes:
            - name: backup
              emptyDir:
                sizeLimit: {{ .sizeLimit | default "10Gi" }}
          {{- with .imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          initContainers:
            - name: backup-runner
              image: {{ .image | default $.Values.dumpImage }}
              imagePullPolicy: IfNotPresent
              volumeMounts:
                - name: backup
                  mountPath: {{ $backupDirectory }}
              env:
                - name: BACKUP_DIR
                  value: {{ $backupDirectory }}
                - name: DB_NAME
                  value: {{ .db.name }}
                - name: DB_USER
                  value: {{ .db.user }}
                - name: DB_HOST
                  value: {{ .db.host }}
                - name: PGPASSWORD
                {{- with .db.password }}
                  {{- toYaml . | nindent 18 }}
                {{- end }}
              command:
                - /bin/bash
                - -c
              args:
                - |
              {{- include "backup.script" . | indent 18 }}
            {{- range $uploadName, $upload := .upload }}
            {{- if and $upload.enabled (eq $upload.type "s3" ) }}
            - name: s3-{{ $uploadName }}-uploader
              image: {{ $upload.image | default $.Values.uploadClientImage }}
              imagePullPolicy: IfNotPresent
              volumeMounts:
                - name: backup
                  mountPath: {{ $backupDirectory }}
              env:
                - name: BACKUP_DIR
                  value: {{ $backupDirectory }}
                - name: MINIO_URL
                  value: {{ $upload.url }}
                - name: MINIO_BUCKET
                  value: {{ $upload.bucket }}
                - name: TARGET_LOCATION
                  value: {{ trimSuffix "/" $upload.targetLocation }}
                - name: MINIO_ACCESS_KEY
                {{- with $upload.accessKey }}
                  {{- toYaml . | nindent 18 }}
                {{- end }}
                - name: MINIO_SECRET_KEY
                {{- with $upload.secretKey }}
                  {{- toYaml . | nindent 18 }}
                {{- end }}
              command:
                - /bin/bash
                - -c
              args:
                - |
              {{- include "backup.upload.skip" $upload | indent 18 }}
              {{- include "backup.upload.s3" . | indent 18 }}
            {{- end }}
            {{- if and $upload.enabled (eq $upload.type "sharepoint" ) }}
            - name: sharepoint-{{ $uploadName }}-uploader
              image: {{ $upload.image }}
              imagePullPolicy: IfNotPresent
              volumeMounts:
                - name: backup
                  mountPath: {{ $backupDirectory }}
              env:
                - name: BACKUP_DIR
                  value: {{ $backupDirectory }}
                - name: MS_TENANT_ID
                  value: {{ $upload.tenantId }}
                - name: SHAREPOINT_DRIVE_ID
                  value: {{ $upload.driveId }}
                - name: SHAREPOINT_FOLDER_PATH
                  value: {{ $upload.targetLocation }}
                - name: MS_CLIENT_ID
                {{- with $upload.clientId }}
                  {{- toYaml . | nindent 18 }}
                {{- end }}
                - name: MS_CLIENT_SECRET
                {{- with $upload.clientSecret }}
                  {{- toYaml . | nindent 18 }}
                {{- end }}
              command:
                - /bin/bash
                - -c
              args:
                - |
              {{- include "backup.upload.skip" $upload | indent 18 }}
              {{- include "backup.upload.sharepoint" . | indent 18 }}
            {{- end }}
            {{- end }}
          containers:
            - name: backup-finalizer
              image: {{ .image }}
              imagePullPolicy: IfNotPresent
              volumeMounts:
                - name: backup
                  mountPath: {{ $backupDirectory }}
              command:
                - /bin/bash
                - -c
              env:
                - name: BACKUP_DIR
                  value: {{ $backupDirectory }}
              args:
                - |
                  cd ${BACKUP_DIR}
                  BACKUP_FILE=$(ls -tp | grep -v / | head -n 1)
                  rm -f "${BACKUP_FILE}"
                  echo "Backup and upload completed successfully!"
{{- end }}
{{- end }}
{{- end }}
