replicaCount: 1
revisionHistoryLimit: 2

image:
  repository: ""
  tag: ""
  pullPolicy: IfNotPresent
imagePullSecrets:
  - name: regcred

securityContext:
   runAsNonRoot: true
   runAsUser: 1000
service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: nginx
  annotations: {}

httproutes:
  enabled: false
  annotations: {}
  gateway:
    name: {}
    namespace: {}
  paths: []
  #  paths:
  #    - path: "/api"
  filters: []
  #  filters:
  #    - type: URLRewrite
  #      urlRewrite:
  #        path:
  #          type: ReplacePrefixMatch
  #          replacePrefixMatch: /api/v1
  timeout: "0s"

envs: {}
envSecrets: {}

resources:
   limits:
     cpu: 200m
     memory: 256Mi
   requests:
     cpu: 100m
     memory: 128Mi

livenessProbe:
  httpGet:
    path: /
    port: 8080
  initialDelaySeconds: 10
  periodSeconds: 20
readinessProbe:
  httpGet:
    path: /
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 20

autoscaling:
  enabled: false
