enabled: true
nameOverride: "dump-postgres"
dumpImage: "bitnami/postgresql"
uploadClientImage: "bitnami/minio-client"
backupDirectory: "/backup"
jobs: []
#  primary:
#    image: "bitnami/postgresql"
#
#    schedule: "0 0 * * *"
#
#    sizeLimit: ""
#    backupDirectory: "/backup"
#
#    db:
#      host: ""
#      name: "postgres"
#      user: "postgres"
#      password: { }
#    #  password:
#    #    valueFrom:
#    #      secretKeyRef:
#    #        name: postgres
#    #        key: password
#    upload:
#      hz-prd:
#        type: s3
#        enabled: true
#        image: "bitnami/minio-client"
#        url: ""
#        bucket: "db-backups"
#        accessKey: { }
#        secretKey: { }
#        targetLocation: ""
#        # With "1 5 7" value backup will run Mon, Fri, Sun
#        backupDays: ""
#
#      sp-prd:
#        type: sharepoint
#        enabled: true
#        image: ""
#        tenantId: ""
#        driveId: ""
#        clientId: { }
#        clientSecret: { }
#        targetLocation: ""
#        backupDays: ""
#
#    imagePullSecrets:
#      - name: regcred
#
#    nodeSelector: { }
#
#    tolerations: [ ]
#
#    affinity: { }
