# Default values for pg-dump-job.
enabled: false
image: ""

imagePullSecrets:
  - name: regcred

nameOverride: ""
fullnameOverride: ""

envs: {}
envSecrets: {}

nodeSelector: {}

tolerations: []

affinity: {}
